sudo: required
language: generic

services:
  - docker


before_install:
  - docker build -t krzysztoflitka/lab3-travis -f Dockerfile.dev2 .

script:
  - docker run -e CI=true krzysztoflitka/lab3-travis npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "lab3-travis"
  env: "Lab3travis-env"
  bucket_name: "lab3-travis"
  bucket_path: "lab3-travis"
  edge: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
