sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t krzysztoflitka/lab3 -f Dockerfile.dev2 .

script:
  - docker run -e CI=true krzysztoflitka/lab3 npm run test
